// The Sheet's data (Monolith MA–MC, from the overnight run): the facts the Sheet shows, drawn from
// .scratch/v1-launch/overnight/monolith/story.md (file dates on Will's PC, content/ai.json, the strip card).
// No write-up exists, so the Sheet opens to the outcome. Media is dev-only under /proto-media (gitignored;
// public/proto-media/monolith/UPLOAD.md lists it for R2).
// Every string is PLACEHOLDER copy, not approved by Will. Tools: the files show Midjourney (stills and video), Nano
// Banana and Premiere Pro; the old site said Luma Dream Machine. Will to confirm (notes.md).
export const _status = 'PLACEHOLDER copy, not approved by Will'

export const B = '/proto-media/monolith/'
export type Pic = { src: string, w: number, h: number, alt: string, srcset: string }
// Each still also has a half-width `-sm` copy; the browser picks by the slot's size (`sizes` in each variant)
const p = (f: string, w: number, h: number, alt: string): Pic => ({
  src: B + f, w, h, alt, srcset: `${B}${f.replace('.webp', '-sm.webp')} ${w / 2}w, ${B}${f} ${w}w`,
})

export const MO = {
  title: 'Monolith Survival',
  year: '2025',
  line: 'A mock campaign for an outdoor brand that doesn\'t exist, with every frame generated by AI.',
  specs: [
    { k: 'Made', v: 'One evening and night, 10 to 11 Sep 2025' },
    { k: 'Tools', v: 'Midjourney (stills and video), Nano Banana, Premiere Pro' },
    { k: 'Film', v: '34 s, 1080 × 1872, 24 fps' },
  ],
  brand: 'The files call the brand VARKON.',
  look: 'White sky, pale stone, one black figure. The red lenses are the only colour.',
  figure: 'Eight portraits of one figure, in the same hood, kit and red lenses.',
  clips: 'About 25 five-second clips in Midjourney video. I kept the best of four each time.',
  edit: 'Cut in Premiere Pro. V1 rendered at 01:39. A 10 s trailer followed in April 2026.',
  prompt: 'the_shoe_stomps_the_ground --ar 9:16 --style raw --v 6.0 (High-motion hiking boot technical gorpcore campaign, massive stone monolith background, slow-motion splash, camera orbits technical shoe)',
  credits: [
    { k: 'Concept, images, film', v: 'William Vernon (solo)' },
    { k: 'Tools', v: 'Midjourney, Nano Banana, Premiere Pro' },
  ],
}

// The outcome and the trailer (portrait 1080 × 1872). The film opens on a grey storm, so its poster is the profile
// shot at 3s (a cut when it starts playing); the trailer's poster is its first frame.
export const FILM = { src: `${B}outcome-film.mp4`, poster: `${B}frame-outcome-3.webp`, w: 1080, h: 1872, label: 'Film, 34 s' }
export const TRAILER = { src: `${B}trailer.mp4`, poster: `${B}poster-trailer.webp`, w: 1080, h: 1872, label: 'Trailer, 10 s' }

// Four of the five-second Midjourney clips, named by their file names. Only the stomp's prompt is known (ai.json).
export const CLIPS = [
  { k: 'Stomp', src: `${B}clip-boot-stomp.mp4`, poster: `${B}poster-clip-boot-stomp.webp` },
  { k: 'Slow motion', src: `${B}clip-slowmo.mp4`, poster: `${B}poster-clip-slowmo.webp` },
  { k: 'Orbit', src: `${B}clip-orbit.mp4`, poster: `${B}poster-clip-orbit.webp` },
  { k: 'Landscape', src: `${B}clip-landscape.mp4`, poster: `${B}poster-clip-landscape.webp` },
]

// The character sheet: VARKON 1–8 (1080 × 1920)
export const FIGURE: Pic[] = [7, 1, 2, 3, 5, 6, 4, 8].map(n => p(`varkon-${n}.webp`, 1080, 1920, `VARKON ${n}: the hooded figure in black kit and red lenses`))

export const WORLD = {
  spires: p('nano-spires-figure.webp', 1024, 1024, 'A lone figure on top of white stone spires'),
  pillar: p('nano-pillar-figure.webp', 1024, 1024, 'The figure standing among pale stone pillars'),
  monoliths: p('nano-monoliths-figure.webp', 1024, 1024, 'The figure small among carved white monoliths'),
  gateway: p('nano-gateway.webp', 1024, 1024, 'A concrete gateway in a pale canyon'),
  steps: p('nano-wall-steps.webp', 1024, 1024, 'Steps cut into a white concrete wall'),
  storm: p('nano-storm.webp', 768, 1344, 'Lightning over a grey sky'),
  cliff: p('nano-cliff.webp', 768, 1344, 'A carved stone cliff in hard light'),
  boot: p('nano-boot.webp', 768, 1344, 'A black hiking boot on pale rock'),
  bootMj: p('mj-boot-closeup.webp', 816, 1456, 'Close-up of the boot on broken stone'),
  canyon: p('mj-canyon.webp', 1024, 1024, 'Concrete monoliths in a canyon, black and white'),
  concrete: p('mj-concrete-figure.webp', 1920, 1920, 'The figure under a concrete overhang'),
  mountains: p('mj-mountains.webp', 1024, 1024, 'Sharp mountain ridges in black and white'),
}

// The night, from the file dates (story.md). No times exist for the Nano Banana edits or the character sheet.
export const NIGHT = [
  { t: '15:16', d: '10 Sep', k: 'Stills', v: 'Midjourney: the figure, then the stone.' },
  { t: '22:33', d: '10 Sep', k: 'Edit', v: 'Premiere project open.' },
  { t: '01:35', d: '11 Sep', k: 'Clips', v: 'Last clip.' },
  { t: '01:39', d: '11 Sep', k: 'Render', v: 'V1 render.' },
  { t: 'Apr', d: '2026', k: 'Trailer', v: 'Recut to a 10 s trailer.' },
]

// Swatches, the median colour of a patch of each still (PIL, 2026-10-06)
export const SWATCH = [
  { k: 'Sky', hex: '#d6d7d7', from: 'VARKON 7, top corner' },
  { k: 'Stone', hex: '#6f7478', from: 'Spires, shaded face' },
  { k: 'Kit', hex: '#454545', from: 'VARKON 7, jacket' },
  { k: 'Lens', hex: '#ca031c', from: 'VARKON 7, right lens' },
]
