/**
 * Typed entry point over src/content/*.json.
 *
 * These files are generated by `npm run content` (redesign/scripts/
 * build_content.py) from the Phase 0 extraction (redesign/content/*.json) —
 * never hand-edit them, and never hand-type copy into them. Run
 * `npm run content:check` after regenerating to confirm 100% parity against
 * redesign/content/INVENTORY.md.
 *
 * A plain typed module rather than an astro:content collection: the source
 * shapes vary per page (case-study process steps, AI-data carousels,
 * STEMS_CONFIG's per-track numeric bounds…) enough that a single Zod schema
 * would either be too loose to help or too strict to survive a re-extraction.
 * These interfaces are a light trust boundary over data that is already
 * verified byte-for-byte against the legacy site, not a runtime validator.
 */
import siteJson from "./site.json";
import homeJson from "./home.json";
import aboutJson from "./about.json";
import workJson from "./work.json";
import projectsJson from "./projects.json";
import aiJson from "./ai.json";
import toolsetJson from "./toolset.json";
import experimentsJson from "./experiments.json";
import tracksJson from "./tracks.json";
import stemsJson from "./stems.json";

/** Every value here can carry a "_src" back to redesign/content/INVENTORY.md
 * ids — kept for traceability, never rendered. */
export type Src = { _src?: string[] };

export interface NavItem extends Src {
  label: string;
  href: string;
}

export interface SocialLink extends Src {
  platform: string;
  href: string;
  label?: string;
  handle?: string;
}

export interface Heading extends Src {
  level: number;
  text: string;
}

export interface TextBlock extends Src {
  tag: string;
  text: string;
}

export interface ImageRef extends Src {
  src: string | null;
  alt?: string | null;
}

/** A structured `media[]` item — a simple image/video/iframe, or a `group`
 * built from an mediaSrc/mediaHtml HTML-string blob (see build_content.py's
 * parse_media_blob). `_todo: true` means Phase 4 needs a bespoke component;
 * `_raw_html` always carries the original markup verbatim as a fallback. */
export interface MediaItem extends Src {
  type: "image" | "video" | "iframe" | "group" | "raw";
  src?: string | null;
  alt?: string | null;
  poster?: string | null;
  title?: string | null;
  layout?: "grid" | "carousel" | "background" | "custom";
  items?: MediaItem[];
  captions?: string[];
  html?: string;
  _raw_html?: string;
  _todo?: true;
}

export interface PageMeta extends Src {
  route: string;
  legacyTitle: string | null;
  headings: Heading[];
}

export interface SiteContent {
  nav: NavItem[];
  socials: SocialLink[];
  /** Shared nav logo (WV monogram), traced to every page's img id. */
  logo: { src: string; alt: string; _src: string[] };
  pages: Record<"index" | "about" | "work" | "projects" | "music" | "ai" | "experiments", PageMeta>;
  ui: Array<{ text: string; page: string; _src: string[] }>;
}

export interface ContactField {
  name: string | null;
  label: string | null;
  placeholder: string | null;
  type: string;
  required: boolean;
}

export interface FeaturedWorkCard extends Src {
  title: string | null;
  label: string | null;
  desc: string | null;
  tags: string[];
  href: string | null;
  media: MediaItem;
}

export interface ToolsetEntry extends Src {
  title: string;
  company: string;
  apps: string;
  logo: string | null;
}

export interface HomeContent {
  headings: Heading[];
  blocks: TextBlock[];
  featuredWork: FeaturedWorkCard[];
  toolset: Record<string, ToolsetEntry>;
  stems: {
    stemsConfig: Record<string, { name: string; file: string }>;
    trackParams: Record<string, Record<string, number | boolean>>;
    fxSliders: Record<string, Array<{ id: string; label: string; min: number; max: number; step: number }>>;
    armedTrackArt?: ImageRef;
    _src: string[];
  };
  contactForm: {
    action: string | null;
    method: string;
    fields: ContactField[];
    submitLabel: string | null;
  };
}

export interface DomPageContent {
  headings: Heading[];
  blocks: TextBlock[];
  images: ImageRef[];
  links: Array<{ text: string | null; href: string } & Src>;
}

export interface WorkPanel extends Src {
  eyebrow: string | null;
  title: string;
  desc: string | null;
  href: string | null;
  media: MediaItem;
}

export interface WorkContent extends DomPageContent {
  panels: WorkPanel[];
}

export interface ProcessStep extends Src {
  num: string;
  title: string;
  text: string;
  media: MediaItem;
}

export interface CaseStudy extends Src {
  id: string;
  slug: string;
  title: string;
  descShort: string;
  descLong: string;
  tags: string[];
  software: string[];
  disciplines: string[];
  outcome: { label: string; media: MediaItem };
  process: ProcessStep[];
  links: string[];
}

export interface ProjectsContent {
  page: { headings: Heading[]; blocks: TextBlock[] };
  softwareKeys: string[];
  disciplineIcons: Record<string, string>;
  softwareLogos: Record<string, string>;
  softwareBadges: Record<string, string>;
  caseStudies: CaseStudy[];
}

export interface AiProject extends Src {
  key: string;
  title: string;
  meta: string;
  tags: string[];
  preview: MediaItem | null;
  media: MediaItem;
  desc: string;
  prompt: string;
  engine: string;
  ar: string;
  style: string;
  upscale: string;
}

export interface AiContent {
  page: { headings: Heading[]; blocks: TextBlock[] };
  projects: AiProject[];
}

export interface ExperimentItem extends Src {
  id: string;
  title: string;
  descShort: string;
  aspectRatio: string;
  software: string[];
  media: MediaItem;
}

export interface ExperimentsContent {
  page: { headings: Heading[]; blocks: TextBlock[] };
  items: ExperimentItem[];
}

export interface Track extends Src {
  title: string;
  soundcloudUrl: string | null;
  audioSrc: string | null;
  artwork: string | null;
  desc: string;
  colors: Array<{ h: number; s: number; l: number }>;
}

export interface TracksContent {
  page: {
    headings: Heading[];
    blocks: TextBlock[];
    images: ImageRef[];
    links: Array<{ text: string; href: string } & Src>;
    embeds: Array<{ src: string | null; title: string | null; testid?: string } & Src>;
  };
  tracks: Track[];
}

export interface StemsContent {
  stemsConfig: Record<string, { name: string; file: string }>;
  trackParams: Record<string, Record<string, number | boolean>>;
  fxSliders: Record<string, Array<{ id: string; label: string; min: number; max: number; step: number }>>;
  _src: string[];
}

export const site = siteJson as unknown as SiteContent;
export const home = homeJson as unknown as HomeContent;
export const about = aboutJson as unknown as DomPageContent;
export const work = workJson as unknown as WorkContent;
export const projects = projectsJson as unknown as ProjectsContent;
export const ai = aiJson as unknown as AiContent;
export const toolset = toolsetJson as unknown as { tools: Record<string, ToolsetEntry> };
export const experiments = experimentsJson as unknown as ExperimentsContent;
export const tracks = tracksJson as unknown as TracksContent;
export const stems = stemsJson as unknown as StemsContent;
